Feature/contacts
ZhengHe-MD/tryMVC pull request #4
Opened 2016-09-19 02:47 UTC by SunnyCat2013

2016-09-19 03:01 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +import FlatButton from 'material-ui/FlatButton';
```javascript
import { Card, CardText } from 'material-ui/Card';
import { List } from 'material-ui/List';
import React, { PropTypes } from 'react';
import ReactDOM from 'react-dom';
import Subheader from 'material-ui/Subheader';
import TextField from 'material-ui/TextField';
import FlatButton from 'material-ui/FlatButton';
```
带括号的先(specific import)，不带的后(default import)。仅仅为了好看一些

2016-09-19 03:02 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +let nextCommentId = 0;
don't use global id, use ```node-uuid```

2016-09-19 03:03 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +let nextCommentId = 0;
generage uuid for each comment
```sh
npm install node-uuid --save
```
```
import uuid from 'node-uuid';
const nextCommentId = uuid.v4();
```

2016-09-19 03:04 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +class Conversation extends React.Component {
you can also
```javascript
import React, { Component, PropTypes } from 'react';
class Conversation extends Component {}
```

2016-09-19 03:05 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +  changeInputValue (e) {
name all your event handler as ```onDoSomething```.
in this specific case, use ```onChangeInputValue```

2016-09-19 03:06 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +  changeInputValue (e) {
or you can use ```onSomethingDone```
in this specific case, use ```onInputValueChanged```
pick whichever you like

2016-09-19 03:07 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +            <CommentBox key={commentObject.id} commentObject={commentObject} store={this.props.store} />
do this when there are more than two props
```javascript
<CommentBox
  key={commentObject.id}
  commentObject={commentObject}
  store={this.props.store}
/>
```

2016-09-19 03:08 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +    const show_comments = this.props.store.getState();
rename all your **show_comments** to **showComments**

2016-09-19 03:10 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +              show_comments.length > 0 ? this.getShowComments(show_comments) : <div><h1>There is no comment.</h1></div>
```javascript
{
  showComments.length > 0 ?
    this.getShowComments(showComments) :
    <div><h1>There is not comment.</h1></div>
}
```
or 
```javascript
{
  showComments.length > 0
    ? this.getShowComments(showComments)
    : <div><h1>There is not comment.</h1></div>
}
```

2016-09-19 03:10 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +              onChange={this.changeInputValue}
event handler naming convention

2016-09-19 03:11 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +      }).catch(error => console.error);
put **.catch** to a new line

2016-09-19 03:11 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +    console.log(userThumbnail);
remove all your console.log

2016-09-19 03:12 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/commentbox.jsx
> +    console.log('username: ' + username);
remove console

2016-09-19 03:13 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/commentbox.jsx
> +    const { id, comment, username, thumbnail } = this.props.commentObject;
you can do this when all variable names are short. But when they are longer, you may
```javascript
const {
  id,
  comment,
  username,
  thumbnail,
} = this.props.commentObject
```

2016-09-19 03:13 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/commentbox.jsx
> +            onClick={() => this.props.store.dispatch({ type: 'DEL_COMMENT', id })}
do you know why you don't have to bind here?

2016-09-19 03:14 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/commentbox.jsx
> +  commentObject: PropTypes.object,
if it is required, put isRequired here

2016-09-19 03:15 UTC, ZhengHe-MD commented on react-redux/contactsMVC/contacts.js
> +      return state.filter( s => s.id !== action.id );
no extra spaces in function call
```javascript
state.filter(s => s.id !== action.id)
```

2016-09-19 03:16 UTC, ZhengHe-MD commented on react-redux/contactsMVC/contacts.js
> +  ];
remove your test data

2016-09-19 03:18 UTC, ZhengHe-MD commented on react-redux/contactsMVC/contacts.js
> +}
put your reducer into another file. you may call it reducer.js in small project.
in large project, you may organise your project in the way introduced here
https://github.com/erikras/ducks-modular-redux

2016-09-19 03:19 UTC, ZhengHe-MD commented on react-redux/contactsMVC/contacts.js
> +);
Put these lines of code into App.js and import from that

2016-09-19 03:20 UTC, ZhengHe-MD commented on react-redux/contactsMVC/package.json
> +    "webpack": "^1.13.2"
webpack, babel-loader, expect should be in devDependencies

2016-09-19 03:20 UTC, ZhengHe-MD commented on react-redux/contactsMVC/package.json
> +    "webpack": "^1.13.2"
use 
```sh
npm install something --save-dev
```
or 
```sh
npm install something -D
```

2016-09-19 03:21 UTC, ZhengHe-MD commented on react-redux/contactsMVC/webpack.config.js
> +  // },
remove commented code

2016-09-19 03:22 UTC, ZhengHe-MD requested changes
You may merge this PR after you fix my comments.
You still need to incorporate
**react-redux**
**redux-thunk**
to complete this project

2016-09-19 12:31 UTC, maicaiyao commented on react-redux/contactsMVC/components/Conversation.jsx
> +  getShowComments(showComments) {
better name? showComments is a verb

2016-09-19 12:33 UTC, maicaiyao commented on react-redux/contactsMVC/components/Conversation.jsx
> +  onGetRandomUser() {
react component should be pure. async operations should be in action creators.

2016-09-19 12:35 UTC, maicaiyao requested changes

2016-09-19 16:15 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +  getShowComments(showComments) {
nice catch.
```getCurrentComments```
```getCommentsToShow```

2016-09-19 16:16 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +  onGetRandomUser() {
he will use redux-thunk to do this in next PR

2016-09-19 16:16 UTC, ZhengHe-MD commented on react-redux/contactsMVC/components/Conversation.jsx
> +  getShowComments(showComments) {
You should do this before you merge

2016-09-20 05:21 UTC, ZhengHe-MD approved these changes

2016-09-20 05:22 UTC, merged